---
- name: Configure web server
  hosts: webservers
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: Running nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Copy html
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
